version: '2'
services:
  app:
    build: .
    command: bin/rails s --binding='0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "80:3000"
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: fake
      RAILS_SERVE_STATIC_FILES: 'true'

#      MYSQL_HOST: mysql
#      MYSQL_PASSWORD:
#
#  mysql:
#    image: mysql
#    command: '--sql_mode=NO_ENGINE_SUBSTITUTION'
#    environment:
#      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#    ports:
#      - "3307:3306"
